app/user/routes.py
from requests import request
from flask import Blueprint, render_template, redirect, url_for, flash, request
user = Blueprint('user', __name__, template_folder='usertemplates', url_prefix='/user')

from .userforms import SignInForm, RegForm, FindPokeForm, BattleForm
from app.models import Pokemon, User, db, Pokedex, Battle
from werkzeug.security import check_password_hash
from flask_login import login_user, current_user, login_required, logout_user


@user.route('/', methods=['GET', 'POST'])
def signin():
    sform = SignInForm()
    if request.method == 'POST':
        if sform.validate_on_submit():
            user = User.query.filter_by(username=sform.username.data).first()
            if user and check_password_hash(user.password, sform.password.data):
                login_user(user)
                flash(f'Welcome back {sform.username.data}!', category='success')
                return redirect(url_for('user.userHome'))
        flash(f"Wrong Username or password.")
        return redirect(url_for('user.signin'))
    return render_template('signin.html', sform=sform)

@user.route('/register', methods=['GET', 'POST'])
def register():
    rform = RegForm()
    if request.method == 'POST':
        if rform.validate_on_submit():
            newuser = User(rform.username.data, rform.email.data, rform.password.data, rform.first_name.data, rform.last_name.data)
            try:
                db.session.add(newuser)
                db.session.commit()
            except:
                flash(f'Username or email has been used previously, please try a different entry!')
                return redirect(url_for('user.register'))
            login_user(newuser)
            flash(f'Registration successful! Welcome {rform.first_name._value()}!', category='success')
            return redirect(url_for('user.userHome'))
        else:
            flash("didn't work!!!!!", category='danger')
            return redirect(url_for('user.register'))
    return render_template('register.html', rform=rform)

@user.route('/logout')
@login_required
def signOut():
    logout_user()
    flash('You have been logged out, please sign back in to access all the fun stuff!', category='warning')
    return redirect(url_for('user.signin'))

@user.route('/userhome', methods=['GET', 'POST'])
@login_required
def userHome():
    fpform = FindPokeForm()
    # catch = Catch()
    dex = Pokedex()
    mydex = Pokedex()
    my_dict = current_user.poke_dict()
    w = current_user.wins
    l = current_user.loses
    if not w:
        w = 0
    if not l:
        l = 0
    for x in my_dict.values():
        if x:
            mydex.add_poke(x)
    if request.method == "POST":
        if request.form.get('catch-btn') == 'catch':
                pname = request.form.get('name-catch')
                if pname not in my_dict:
                    current_user.add_poke(pname)
                    upoke = Pokemon.query.filter(Pokemon.name==pname).first()
                    upoke.catch(current_user.username)
                    flash(f'{pname} caught!', category='success')
                    return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)
                else:
                    flash(f'{pname} already caught!', category='danger')
                    return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)
        
        if request.form.get('release-btn') == 'release':
                pname = request.form.get('name-release')
                current_user.rem_poke(pname)
                upoke = Pokemon.query.filter(Pokemon.name==pname).first()
                upoke.release()
                flash(f'{pname} released!', category='warning')
                return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)

        if fpform.data:
            try:
                dex.add_poke(fpform.data['poke'])
                return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)
            except:
                flash(f'Poke not found, try again!', category='danger')
                return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)
  
    flash('Welcome back!', category='success')
    return render_template('userhome.html', my_dict=my_dict, dex=dex, fpform=fpform, mydex=mydex, w=w, l=l)

@user.route('/battle', methods=['GET', 'POST'])
@login_required
def battle():
    bform = BattleForm()
    ulist1 = db.session.query(User.username).all()
    ulist = list(map(lambda x: str(x)[2:-3], ulist1))
    cuserdex = Pokedex()
    oppuserdex = Pokedex()
    un = current_user.username
    my_dict = current_user.poke_dict()
    oppname = None
    w = current_user.wins
    l = current_user.loses
    if not w:
        w = 0
    if not l:
        l = 0
    for x in my_dict.values():
        if x:
            cuserdex.add_poke(x)
    print(oppname)
    if request.method == "POST":
        if request.form.get('catch-btn'):
            oppname = request.form.get('catch-btn')
            opp_user = User.query.filter(User.username==oppname).first()
            opp_pokes = opp_user.poke_dict()
            opw = opp_user.wins
            opl = opp_user.loses
            if not opw:
                opw = 0
            if not opl:
                opl = 0
            print(opp_pokes, oppname, opp_user)
            for x in opp_pokes.values():
                if x:
                    oppuserdex.add_poke(x)
            return render_template('battle.html', ulist=ulist, cuserdex=cuserdex, oppuserdex=oppuserdex, oppname=oppname, bform=bform, opp_user=opp_user, w=w, l=l, opw=opw, opl=opl)
            
        if bform.data:
            print(f'\nBform data-\t{bform.data}')
            oppname = bform.data['opp']
            opp_user = User.query.filter(User.username==oppname).first()
            opp_dict = opp_user.poke_dict()
            opw = opp_user.wins
            opl = opp_user.loses
            if not opw:
                opw = 0
            if not opl:
                opl = 0
            for x in opp_dict.values():
                if x:
                    oppuserdex.add_poke(x)
            b = Battle(cuserdex, oppuserdex, un, oppname)
            b.run()
            
            print(oppname, opp_user)
            summ = b.summary
            print(summ)
            if summ['winner'] == un:
                current_user.winner()
                opp_user.loser()
            elif summ['winner'] == oppname:
                current_user.loser()
                opp_user.winner()
            flash(f"{summ['winner']} WON THE BATTLE!!!", category='success')
            flash(f"It's a sad day for {summ['loser']}, they lost. . .", category='warning')
            return render_template('battle.html', b=b, summ=summ, ulist=ulist, cuserdex=cuserdex, oppuserdex=oppuserdex, oppname=oppname, opp_user=opp_user, bform=bform, w=w, l=l, opw=opw, opl=opl)
            

            
    return render_template('battle.html', ulist=ulist, cuserdex=cuserdex, oppuserdex=oppuserdex, oppname=oppname, bform=bform, w=w, l=l)

app/templates/components/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poke - a - mon</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
        integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../static/css/layout.css">
    {% block head %}

    {% endblock %}
</head>

<body>
    <nav id="nav" class="navbar navbar-danger bg-danger">
        <div id="nav-cont" class="container-fluid bg-danger">
            <span class="navbar-brand mb-0 h1 bg-danger">Poke-<strong class="bg-danger">Battle!</strong> </span>

            {% if current_user.is_authenticated %}
            <a id="battletag" class="nav-link bg-danger" href="{{ url_for('user.battle') }}">Go to Battle!</a>
            <a id="usertag" class="nav-link bg-danger" href="{{ url_for('user.userHome')}}">{{current_user.username}}</a>
            <a id="logout" class="nav-link bg-danger" href="{{ url_for('user.signOut')}}">Logout</a>
            {% else %}
            <a id="signintag" class="nav-link bg-danger" href="{{ url_for('user.signin')}}">Sign In</a>
            <a id="registertag" class="nav-link bg-danger" href="{{ url_for('user.register')}}">Register</a>
            {% endif %}
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row justify-content-center">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    {% block content %}
    {% endblock %}

    {% block content2 %}
    {% endblock %}

    {% block content3 %}
    {% endblock %}


</body>

</html>